services:
    idp:
        container_name: idp
        image: ghcr.io/identicum/keycloak:26.1
        restart: always
        pull_policy: always
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        volumes:
            - ./keycloak/:/opt/keycloak/data/import/
        command: "start-dev --import-realm"
        ports:
            - 8080:8080
    demoapp:
        container_name: demoapp
        # image: ghcr.io/identicum/saml-demoapp-java:latest
        build: .
        restart: always
        ports:
            - 8081:8080
        environment:
            - ONELOGIN_SAML2_SP_ENTITYID=http://demoapp1:8081/
            - ONELOGIN_SAML2_SP_ASSERTION_CONSUMER_SERVICE_URL=http://demoapp1:8081/acs.jsp
            - ONELOGIN_SAML2_SP_SINGLE_LOGOUT_SERVICE_URL=http://demoapp1:8081/sls.jsp
            - IDP_ENTITY_DESCRIPTOR=http://idp:8080/realms/demorealm/protocol/saml/descriptor
        depends_on:
            idp:
                condition: service_healthy