name: Analyze code and update Docker image
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pom.xml'
env:
  CONTAINER_IMAGE: identicum/${{github.event.repository.name}}:latest
jobs:
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  build-push:
    name: Build docker image and push to DockerHub registry
    needs: analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Hub login
      run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
    - name: Build image 
      run: docker build -t $CONTAINER_IMAGE .
      working-directory: .
    - name: Push to Docker Hub
      run: docker push $CONTAINER_IMAGE